addSbtPlugin("com.eed3si9n"        % "sbt-assembly"   % "1.0.0")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"  % "0.10.0")
addSbtPlugin("com.geirsson"        % "sbt-ci-release" % "1.5.7")
addSbtPlugin("org.scoverage"       % "sbt-scoverage"  % "1.8.2")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"   % "0.9.29")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"   % "2.4.3")
addSbtPlugin("com.beautiful-scala" % "sbt-scalastyle" % "1.5.0")
