addSbtPlugin("com.eed3si9n"        % "sbt-assembly"   % "0.15.0")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"  % "0.9.0")
addSbtPlugin("com.geirsson"        % "sbt-ci-release" % "1.5.3")
addSbtPlugin("org.scoverage"       % "sbt-scoverage"  % "1.6.1")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"   % "0.9.16")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"   % "2.4.0")
addSbtPlugin("com.beautiful-scala" % "sbt-scalastyle" % "1.4.0")
